class_names = [   {   'name': 'Banh canh (Vietnamese thick noodle soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 200,
                         'Fat': 7,
                         'Saturates': 1.5,
                         'Sugar': 2,
                         'Salt': 0.7,
                         'Protein': 8}},
    {   'name': 'Banh chung (Square sticky rice cake)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 600,
                         'Fat': 10,
                         'Saturates': 3,
                         'Sugar': 1,
                         'Salt': 1.2,
                         'Protein': 12}},
    {   'name': 'Banh cuon (Rolled rice pancake)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 300,
                         'Fat': 8,
                         'Saturates': 2,
                         'Sugar': 2,
                         'Salt': 0.8,
                         'Protein': 6}},
    {   'name': 'Banh khot (Mini savory pancakes)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 400,
                         'Fat': 15,
                         'Saturates': 3,
                         'Sugar': 3,
                         'Salt': 1,
                         'Protein': 5}},
    {   'name': 'Banh mi (Vietnamese baguette sandwich)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 350,
                         'Fat': 12,
                         'Saturates': 4,
                         'Sugar': 4,
                         'Salt': 1.5,
                         'Protein': 10}},
    {   'name': 'Banh trang (Rice paper)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 300,
                         'Fat': 0.5,
                         'Saturates': 0.1,
                         'Sugar': 0,
                         'Salt': 0.2,
                         'Protein': 1}},
    {   'name': 'Banh trang tron (Rice paper salad)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 250,
                         'Fat': 10,
                         'Saturates': 1.5,
                         'Sugar': 3,
                         'Salt': 1,
                         'Protein': 6}},
    {   'name': 'Banh xeo (Vietnamese sizzling pancake)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 400,
                         'Fat': 16,
                         'Saturates': 4,
                         'Sugar': 3,
                         'Salt': 1.5,
                         'Protein': 10}},
    {   'name': 'Bo kho (Beef stew)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 450,
                         'Fat': 20,
                         'Saturates': 8,
                         'Sugar': 5,
                         'Salt': 2,
                         'Protein': 25}},
    {   'name': 'Bo la lot (Grilled beef wrapped in betel leaves)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 300,
                         'Fat': 12,
                         'Saturates': 4,
                         'Sugar': 2,
                         'Salt': 1,
                         'Protein': 15}},
    {   'name': 'Bong cai (Cauliflower)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 25,
                         'Fat': 0.1,
                         'Saturates': 0,
                         'Sugar': 2,
                         'Salt': 0,
                         'Protein': 2}},
    {   'name': 'Bun (Rice vermicelli)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 110,
                         'Fat': 0.5,
                         'Saturates': 0.1,
                         'Sugar': 0.5,
                         'Salt': 0.1,
                         'Protein': 2}},
    {   'name': 'Bun bo Hue (Hue beef noodle soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 500,
                         'Fat': 15,
                         'Saturates': 5,
                         'Sugar': 4,
                         'Salt': 2.5,
                         'Protein': 22}},
    {   'name': 'Bun cha (Grilled pork with vermicelli)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 550,
                         'Fat': 25,
                         'Saturates': 8,
                         'Sugar': 6,
                         'Salt': 2.5,
                         'Protein': 20}},
    {   'name': 'Bun dau (Vermicelli with tofu)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 400,
                         'Fat': 20,
                         'Saturates': 3.5,
                         'Sugar': 4,
                         'Salt': 1.8,
                         'Protein': 15}},
    {   'name': 'Bun mam (Fermented fish noodle soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 600,
                         'Fat': 20,
                         'Saturates': 5,
                         'Sugar': 6,
                         'Salt': 2.5,
                         'Protein': 18}},
    {   'name': 'Bun rieu (Crab noodle soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 500,
                         'Fat': 18,
                         'Saturates': 4,
                         'Sugar': 4,
                         'Salt': 2.2,
                         'Protein': 16}},
    {   'name': 'Ca (Fish)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 150,
                         'Fat': 4,
                         'Saturates': 1,
                         'Sugar': 0,
                         'Salt': 0.5,
                         'Protein': 22}},
    {   'name': 'Ca chua (Tomato)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 18,
                         'Fat': 0.2,
                         'Saturates': 0,
                         'Sugar': 2.6,
                         'Salt': 0,
                         'Protein': 1}},
    {   'name': 'Ca phao (Pickled eggplant)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 30,
                         'Fat': 0.2,
                         'Saturates': 0,
                         'Sugar': 2,
                         'Salt': 0.6,
                         'Protein': 1}},
    {   'name': 'Ca rot (Carrot)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 41,
                         'Fat': 0.2,
                         'Saturates': 0,
                         'Sugar': 4.7,
                         'Salt': 0,
                         'Protein': 1}},
    {   'name': 'Canh (Soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 100,
                         'Fat': 3,
                         'Saturates': 0.5,
                         'Sugar': 2,
                         'Salt': 0.8,
                         'Protein': 4}},
    {   'name': 'Cha (Vietnamese pork roll)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 250,
                         'Fat': 20,
                         'Saturates': 7,
                         'Sugar': 1,
                         'Salt': 1.2,
                         'Protein': 12}},
    {   'name': 'Cha gio (Spring rolls)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 150,
                         'Fat': 8,
                         'Saturates': 2,
                         'Sugar': 1,
                         'Salt': 0.5,
                         'Protein': 8}},
    {   'name': 'Chanh (Lime)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 30,
                         'Fat': 0.2,
                         'Saturates': 0,
                         'Sugar': 1.7,
                         'Salt': 0.03,
                         'Protein': 0.5}},
    {   'name': 'Com (Rice)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 130,
                         'Fat': 0.3,
                         'Saturates': 0,
                         'Sugar': 0,
                         'Salt': 0,
                         'Protein': 4}},
    {   'name': 'Com tam (Broken rice)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 700,
                         'Fat': 20,
                         'Saturates': 7,
                         'Sugar': 5,
                         'Salt': 2,
                         'Protein': 25}},
    {   'name': 'Con nguoi (Human)',
        'serving_type': 'N/A',
        'nutrition': {   'Calories': 0,
                         'Fat': 0,
                         'Saturates': 0,
                         'Sugar': 0,
                         'Salt': 0,
                         'Protein': 0}},
    {   'name': 'Cu kieu (Pickled scallion head)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 20,
                         'Fat': 0.1,
                         'Saturates': 0,
                         'Sugar': 1,
                         'Salt': 1,
                         'Protein': 0.5}},
    {   'name': 'Cua (Crab)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 97,
                         'Fat': 1.5,
                         'Saturates': 0.2,
                         'Sugar': 0,
                         'Salt': 0.4,
                         'Protein': 18}},
    {   'name': 'Dau hu (Tofu)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 76,
                         'Fat': 4.8,
                         'Saturates': 0.7,
                         'Sugar': 0.3,
                         'Salt': 0.01,
                         'Protein': 8}},
    {   'name': 'Dua chua (Pickled vegetables)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 25,
                         'Fat': 0.1,
                         'Saturates': 0,
                         'Sugar': 2,
                         'Salt': 1.5,
                         'Protein': 1}},
    {   'name': 'Dua leo (Cucumber)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 16,
                         'Fat': 0.1,
                         'Saturates': 0,
                         'Sugar': 1.7,
                         'Salt': 0,
                         'Protein': 0.5}},
    {   'name': 'Goi cuon (Fresh spring rolls)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 100,
                         'Fat': 2,
                         'Saturates': 0.5,
                         'Sugar': 1,
                         'Salt': 0.5,
                         'Protein': 6}},
    {   'name': 'Hamburger',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 350,
                         'Fat': 20,
                         'Saturates': 8,
                         'Sugar': 5,
                         'Salt': 1.8,
                         'Protein': 18}},
    {   'name': 'Heo quay (Roast pork)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 330,
                         'Fat': 28,
                         'Saturates': 10,
                         'Sugar': 0,
                         'Salt': 1.1,
                         'Protein': 20}},
    {   'name': 'Hu tieu (Clear rice noodle soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 400,
                         'Fat': 10,
                         'Saturates': 2,
                         'Sugar': 3,
                         'Salt': 2,
                         'Protein': 15}},
    {   'name': 'Kho qua thit (Stuffed bitter melon soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 250,
                         'Fat': 7,
                         'Saturates': 2,
                         'Sugar': 2,
                         'Salt': 1.3,
                         'Protein': 10}},
    {   'name': 'Khoai tay chien (French fries)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 312,
                         'Fat': 15,
                         'Saturates': 2,
                         'Sugar': 0.4,
                         'Salt': 0.5,
                         'Protein': 3}},
    {   'name': 'Lau (Hotpot)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 600,
                         'Fat': 20,
                         'Saturates': 5,
                         'Sugar': 4,
                         'Salt': 3,
                         'Protein': 30}},
    {   'name': 'Long heo (Pork offal)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 250,
                         'Fat': 20,
                         'Saturates': 7,
                         'Sugar': 0,
                         'Salt': 0.9,
                         'Protein': 16}},
    {   'name': 'Mi (Egg noodles)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 138,
                         'Fat': 2,
                         'Saturates': 0.5,
                         'Sugar': 0.2,
                         'Salt': 0.6,
                         'Protein': 5}},
    {   'name': 'Muc (Squid)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 92,
                         'Fat': 1.4,
                         'Saturates': 0.5,
                         'Sugar': 0,
                         'Salt': 0.3,
                         'Protein': 16}},
    {   'name': 'Nam (Mushroom)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 22,
                         'Fat': 0.1,
                         'Saturates': 0,
                         'Sugar': 1.8,
                         'Salt': 0.01,
                         'Protein': 3}},
    {   'name': 'Oc (Snails)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 79,
                         'Fat': 1.4,
                         'Saturates': 0.3,
                         'Sugar': 0,
                         'Salt': 0.4,
                         'Protein': 15}},
    {   'name': 'Ot chuong (Bell pepper)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 20,
                         'Fat': 0.2,
                         'Saturates': 0,
                         'Sugar': 4.2,
                         'Salt': 0.02,
                         'Protein': 1}},
    {   'name': 'Pho (Vietnamese noodle soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 450,
                         'Fat': 15,
                         'Saturates': 5,
                         'Sugar': 3,
                         'Salt': 1.8,
                         'Protein': 20}},
    {   'name': 'Pho mai (Cheese)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 400,
                         'Fat': 33,
                         'Saturates': 21,
                         'Sugar': 1.5,
                         'Salt': 1.8,
                         'Protein': 25}},
    {   'name': 'Rau (Vegetables)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 25,
                         'Fat': 0.2,
                         'Saturates': 0,
                         'Sugar': 2,
                         'Salt': 0.02,
                         'Protein': 1.5}},
    {   'name': 'Salad (Salad)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 150,
                         'Fat': 10,
                         'Saturates': 2,
                         'Sugar': 2,
                         'Salt': 0.6,
                         'Protein': 1.5}},
    {   'name': 'Thit bo (Beef)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 250,
                         'Fat': 15,
                         'Saturates': 6,
                         'Sugar': 0,
                         'Salt': 0.5,
                         'Protein': 26}},
    {   'name': 'Thit ga (Chicken)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 239,
                         'Fat': 13.6,
                         'Saturates': 3.8,
                         'Sugar': 0,
                         'Salt': 0.7,
                         'Protein': 27}},
    {   'name': 'Thit heo (Pork)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 242,
                         'Fat': 14,
                         'Saturates': 5,
                         'Sugar': 0,
                         'Salt': 0.6,
                         'Protein': 25}},
    {   'name': 'Thit kho (Braised pork)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 500,
                         'Fat': 30,
                         'Saturates': 10,
                         'Sugar': 5,
                         'Salt': 2,
                         'Protein': 18}},
    {   'name': 'Thit nuong (Grilled meat)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 400,
                         'Fat': 20,
                         'Saturates': 7,
                         'Sugar': 3,
                         'Salt': 1.5,
                         'Protein': 22}},
    {   'name': 'Tom (Shrimp)',
        'serving_type': 'per 100g',
        'nutrition': {   'Calories': 99,
                         'Fat': 1,
                         'Saturates': 0.3,
                         'Sugar': 0,
                         'Salt': 0.4,
                         'Protein': 24}},
    {   'name': 'Trung (Egg)',
        'serving_type': '1 Egg',
        'nutrition': {   'Calories': 75,
                         'Fat': 11,
                         'Saturates': 3.3,
                         'Sugar': 1.1,
                         'Salt': 0.12,
                         'Protein': 6}},
    {   'name': 'Xoi (Sticky rice)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 180,
                         'Fat': 0.3,
                         'Saturates': 0,
                         'Sugar': 0.1,
                         'Salt': 0.04,
                         'Protein': 6}},
    {   'name': 'Banh beo (Vietnamese savory steamed rice cake)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 120,
                         'Fat': 4,
                         'Saturates': 1,
                         'Sugar': 1.5,
                         'Salt': 0.3,
                         'Protein': 4}},
    {   'name': 'Cao lau (Cao lau noodles)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 350,
                         'Fat': 10,
                         'Saturates': 2.5,
                         'Sugar': 2,
                         'Salt': 1.4,
                         'Protein': 18}},
    {   'name': 'Mi Quang (Quang-style noodles)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 400,
                         'Fat': 12,
                         'Saturates': 3,
                         'Sugar': 3,
                         'Salt': 1.8,
                         'Protein': 16}},
    {   'name': 'Com chien duong chau (Yangzhou fried rice)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 600,
                         'Fat': 20,
                         'Saturates': 4,
                         'Sugar': 4,
                         'Salt': 2.2,
                         'Protein': 12}},
    {   'name': 'Bun cha ca (Fish cake noodle soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 500,
                         'Fat': 15,
                         'Saturates': 4,
                         'Sugar': 3,
                         'Salt': 1.9,
                         'Protein': 15}},
    {   'name': 'Com chien ga (Fried rice with chicken)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 700,
                         'Fat': 25,
                         'Saturates': 5,
                         'Sugar': 4,
                         'Salt': 2.5,
                         'Protein': 18}},
    {   'name': 'Chao long (Pork organ congee)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 400,
                         'Fat': 10,
                         'Saturates': 2,
                         'Sugar': 1.5,
                         'Salt': 1.2,
                         'Protein': 14}},
    {   'name': 'Nom hoa chuoi (Banana blossom salad)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 150,
                         'Fat': 7,
                         'Saturates': 1,
                         'Sugar': 2,
                         'Salt': 1,
                         'Protein': 5}},
    {   'name': 'Nui xao bo (Stir-fried macaroni with beef)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 550,
                         'Fat': 18,
                         'Saturates': 6,
                         'Sugar': 3,
                         'Salt': 2.1,
                         'Protein': 22}},
    {   'name': 'Sup cua (Crab soup)',
        'serving_type': '1 serving',
        'nutrition': {   'Calories': 200,
                         'Fat': 5,
                         'Saturates': 1,
                         'Sugar': 1.5,
                         'Salt': 0.9,
                         'Protein': 8}}]
