"""VietFood68 class metadata and nutrition reference (Phase 3 Runtime Projection).

IMPORTANT ARCHITECTURAL NOTE:
  This file is a RUNTIME PROJECTION / IN-MEMORY CACHE.
  The Single Source of Truth (SSOT) is data/nin_nutrition_canonical.json and data/vietfood68_nin_mapping.json.
  Do not edit values here manually; re-run `python scripts/update_class_names_nin.py`.

Target Nutrient Schema (12 nutrients):
  - Macros (g) & Energy (kcal): Calories, Protein, Fat, Carbs, Saturates, Sugar, Salt
  - Micronutrients (mg): Sodium, Calcium, Iron, Zinc, Cholesterol
"""

ALLOWED_SOURCES = {"usda_fdc", "vn_nin_2017", "literature", "literature_fallback", "non_food", "not_applicable"}

NUTRITION_SOURCES = {
    "Banh beo (Vietnamese savory steamed rice cake)": ("vn_nin_2017", "NIN: Bánh bèo (nin_dish_6911b07c668d1a5d170be115) [basis: per_100g]"),
    "Banh canh (Vietnamese thick noodle soup)": ("vn_nin_2017", "NIN: Bánh canh thịt heo (nin_dish_6945280a396fdfd8c109b2fa) [basis: per_100g]"),
    "Banh chung (Square sticky rice cake)": ("vn_nin_2017", "NIN: Bánh chưng cỡ vừa (nin_dish_69491c415756e8e52e0ec993) [basis: per_100g]"),
    "Banh cuon (Rolled rice pancake)": ("vn_nin_2017", "NIN: Bánh cuốn thịt (nin_dish_69491e3f2eb544b04a0add82) [basis: per_100g]"),
    "Banh khot (Mini savory pancakes)": ("literature_fallback", "Bảng phân tích thành phần món ăn Việt Nam (Bộ Y Tế - NIN & Composite recipes) [basis: per_100g]"),
    "Banh mi (Vietnamese baguette sandwich)": ("vn_nin_2017", "NIN: Bánh mỳ pate trứng (nin_dish_6937cc55bb1269d4c706878a) [basis: per_100g]"),
    "Banh trang (Rice paper)": ("vn_nin_2017", "NIN: Bánh đa nem (nin_ing_6877a6b660d6c84e9bd5cacc) [basis: per_100g]"),
    "Banh trang tron (Rice paper salad)": ("vn_nin_2017", "NIN: Bánh tráng trộn (nin_dish_6937d0e889b64dde6009d507) [basis: per_100g]"),
    "Banh xeo (Vietnamese sizzling pancake)": ("vn_nin_2017", "NIN: Bánh xèo (nin_dish_694e064bba5c59be9d0c5942) [basis: per_100g]"),
    "Bo kho (Beef stew)": ("vn_nin_2017", "NIN: Bánh mỳ sốt vang (nin_dish_694bc1b51cc4830b4507fa53) [basis: per_100g]"),
    "Bo la lot (Grilled beef wrapped in betel leaves)": ("vn_nin_2017", "NIN: Cơm suất (sườn, đậu, chả lá lốt) (nin_dish_69043ff355955b7f120af7b4) [basis: per_100g]"),
    "Bong cai (Cauliflower)": ("vn_nin_2017", "NIN: Súp lơ trắng, tươi (nin_ing_6877a6b660d6c84e9bd5cb7d) [basis: per_100g]"),
    "Bun (Rice vermicelli)": ("vn_nin_2017", "NIN: Bún, tươi (nin_ing_6877a6b660d6c84e9bd5cad6) [basis: per_100g]"),
    "Bun bo Hue (Hue beef noodle soup)": ("vn_nin_2017", "NIN: Bún bò giò heo (Huế) (nin_dish_6947cd314776d891e209df93) [basis: per_100g]"),
    "Bun cha (Grilled pork with vermicelli)": ("vn_nin_2017", "NIN: Bún chả (nin_dish_6947db28eeaad7e26b0eb372) [basis: per_100g]"),
    "Bun cha ca (Fish cake noodle soup)": ("vn_nin_2017", "NIN: Bún chả cá (nin_dish_6947d40fa5cc4fdc720ebd82) [basis: per_100g]"),
    "Bun dau (Vermicelli with tofu)": ("vn_nin_2017", "NIN: Bún đậu mắm tôm (nin_dish_6947df802729431e960491d3) [basis: per_100g]"),
    "Bun mam (Fermented fish noodle soup)": ("vn_nin_2017", "NIN: Bún mắm (nin_dish_68786acb1767a9925a0e7d78) [basis: per_100g]"),
    "Bun rieu (Crab noodle soup)": ("vn_nin_2017", "NIN: Bún riêu cua (nin_dish_6947e5ff511f8f0de60d7164) [basis: per_100g]"),
    "Ca (Fish)": ("vn_nin_2017", "NIN: Cá chép, tươi (nin_ing_6877a6b660d6c84e9bd5cc54) [basis: per_100g]"),
    "Ca chua (Tomato)": ("vn_nin_2017", "NIN: Quả cà chua, tươi (nin_ing_6877a6b660d6c84e9bd5cb1f) [basis: per_100g]"),
    "Ca phao (Pickled eggplant)": ("vn_nin_2017", "NIN: Cà pháo, muối nén (nin_ing_6877a6b660d6c84e9bd5cb8b) [basis: per_100g]"),
    "Ca rot (Carrot)": ("vn_nin_2017", "NIN: Củ cà rốt, tươi (nin_ing_6877a6b660d6c84e9bd5cb21) [basis: per_100g]"),
    "Canh (Soup)": ("vn_nin_2017", "NIN: Canh rau ngót nấu thịt (nin_dish_693a43e057dc35b55101fbf2) [basis: per_100g_mapping_derived]"),
    "Cao lau (Cao lau noodles)": ("literature_fallback", "Tài liệu dinh dưỡng ẩm thực Hội An - Quảng Nam (Composite recipes) [basis: per_100g]"),
    "Cha (Vietnamese pork roll)": ("vn_nin_2017", "NIN: Giò lụa, chín (nin_ing_6877a6b660d6c84e9bd5cc30) [basis: per_100g]"),
    "Cha gio (Spring rolls)": ("vn_nin_2017", "NIN: Nem rán / Chả giò chiên (nin_dish_693b878a51af016fd5080c83) [basis: per_100g_mapping_derived]"),
    "Chanh (Lime)": ("vn_nin_2017", "NIN: Chanh, tươi (nin_ing_6877a6b660d6c84e9bd5cba4) [basis: per_100g]"),
    "Chao long (Pork organ congee)": ("vn_nin_2017", "NIN: Cháo lòng (nin_dish_6948020ae0a4ed42970317eb) [basis: per_100g]"),
    "Com (Rice)": ("vn_nin_2017", "NIN: Cơm tẻ miệng bát (nin_dish_68f8aadc094e90b19f042a82) [basis: per_100g]"),
    "Com chien duong chau (Yangzhou fried rice)": ("vn_nin_2017", "NIN: Cơm rang thập cẩm (nin_dish_693a27498bbe5e3730065343) [basis: per_100g]"),
    "Com chien ga (Fried rice with chicken)": ("vn_nin_2017", "NIN: Cơm gà (nin_dish_68a683a410eddb46cf0f71a3) [basis: per_100g]"),
    "Com tam (Broken rice)": ("vn_nin_2017", "NIN: Cơm sườn (nin_dish_693a2a2959d546807301b0c4) [basis: per_100g]"),
    "Con nguoi (Human)": ("non_food", "Non-food background class — zero nutrient values [basis: per_100g]"),
    "Cu kieu (Pickled scallion head)": ("vn_nin_2017", "NIN: Kiệu, muối (nin_ing_6877a6b660d6c84e9bd5cb93) [basis: per_100g]"),
    "Cua (Crab)": ("vn_nin_2017", "NIN: Cua đồng, tươi (nin_ing_6877a6b660d6c84e9bd5cc73) [basis: per_100g]"),
    "Dau hu (Tofu)": ("vn_nin_2017", "NIN: Đậu phụ, sống (nin_ing_6877a6b660d6c84e9bd5cb11) [basis: per_100g]"),
    "Dua chua (Pickled vegetables)": ("vn_nin_2017", "NIN: Dưa cải bẹ (nin_ing_6877a6b660d6c84e9bd5cb8e) [basis: per_100g]"),
    "Dua leo (Cucumber)": ("vn_nin_2017", "NIN: Dưa chuột, tươi (nin_ing_6877a6b660d6c84e9bd5cb35) [basis: per_100g]"),
    "Goi cuon (Fresh spring rolls)": ("vn_nin_2017", "NIN: Bánh tráng trộn (nin_dish_6937d0e889b64dde6009d507) [basis: per_100g]"),
    "Hamburger": ("vn_nin_2017", "NIN: Hamburger lợn (nin_dish_68a54029f57bee55470387d2) [basis: per_100g]"),
    "Heo quay (Roast pork)": ("vn_nin_2017", "NIN: Thịt lợn quay (nin_dish_6937da5ee8ba4488430222d8) [basis: per_100g_mapping_derived]"),
    "Hu tieu (Clear rice noodle soup)": ("vn_nin_2017", "NIN: Hủ tiếu Nam vang nước (nin_dish_68f9a0c0a4c9392ea30c4f32) [basis: per_100g]"),
    "Kho qua thit (Stuffed bitter melon soup)": ("vn_nin_2017", "NIN: Canh khổ qua (mướp đắng) nhồi thịt (nin_dish_693a40f6bb10bc44d2078612) [basis: per_100g_mapping_derived]"),
    "Khoai tay chien (French fries)": ("vn_nin_2017", "NIN: Khoai tây chiên (nin_dish_693b857f273f8370c302e6ce) [basis: per_100g_mapping_derived]"),
    "Lau (Hotpot)": ("vn_nin_2017", "NIN: Lẩu thập cẩm (nin_dish_6948cd812eb544b04a0add76) [basis: per_100g]"),
    "Long heo (Pork offal)": ("vn_nin_2017", "NIN: Lòng lợn luộc (nin_dish_693a83606b1977ca8d0de216) [basis: per_100g_mapping_derived]"),
    "Mi (Egg noodles)": ("vn_nin_2017", "NIN: Mỳ sợi, khô (nin_ing_6877a6b660d6c84e9bd5cad8) [basis: per_100g]"),
    "Mi Quang (Quang-style noodles)": ("vn_nin_2017", "NIN: Mỳ Quảng (nin_dish_694818d0c2bdd1529907c387) [basis: per_100g]"),
    "Muc (Squid)": ("vn_nin_2017", "NIN: Mực, tươi (nin_ing_6877a6b660d6c84e9bd5cc79) [basis: per_100g]"),
    "Nam (Mushroom)": ("vn_nin_2017", "NIN: Nấm hương, tươi (nin_ing_6877a6b660d6c84e9bd5cb99) [basis: per_100g]"),
    "Nom hoa chuoi (Banana blossom salad)": ("vn_nin_2017", "NIN: Nộm hoa chuối thịt gà (nin_dish_694522f0396fdfd8c109b2f4) [basis: per_100g_mapping_derived]"),
    "Nui xao bo (Stir-fried macaroni with beef)": ("vn_nin_2017", "NIN: Nui, luộc (nin_ing_6877a6b660d6c84e9bd5cd8f) [basis: per_100g]"),
    "Oc (Snails)": ("vn_nin_2017", "NIN: Ốc nhồi, tươi (nin_ing_6877a6b660d6c84e9bd5cc7c) [basis: per_100g]"),
    "Ot chuong (Bell pepper)": ("vn_nin_2017", "NIN: Ớt xanh to, tươi (nin_ing_6877a6b660d6c84e9bd5cb59) [basis: per_100g]"),
    "Pho (Vietnamese noodle soup)": ("vn_nin_2017", "NIN: Phở bò chín (nin_dish_68f890821eff1748460a2632) [basis: per_100g]"),
    "Pho mai (Cheese)": ("vn_nin_2017", "NIN: Phô mai tam giác (nin_dish_69512eb4a0cfb0866108cb79) [basis: per_100g]"),
    "Rau (Vegetables)": ("vn_nin_2017", "NIN: Rau muống,  tươi (nin_ing_6877a6b660d6c84e9bd5cb6d) [basis: per_100g]"),
    "Salad (Salad)": ("vn_nin_2017", "NIN: Salad rau củ (nin_dish_694524cacd788cb7ad036fb4) [basis: per_100g_mapping_derived]"),
    "Sup cua (Crab soup)": ("vn_nin_2017", "NIN: Súp ngô cua (nin_dish_6948122f2eb544b04a0add72) [basis: per_100g]"),
    "Thit bo (Beef)": ("vn_nin_2017", "NIN: Thịt bò, loại I, tươi (nin_ing_6877a6b660d6c84e9bd5cbee) [basis: per_100g]"),
    "Thit ga (Chicken)": ("vn_nin_2017", "NIN: Thịt gà ta, tươi (nin_ing_6877a6b660d6c84e9bd5cbf8) [basis: per_100g]"),
    "Thit heo (Pork)": ("vn_nin_2017", "NIN: Thịt lợn nạc vai, luộc (nin_ing_6877a6b660d6c84e9bd5cde4) [basis: per_100g]"),
    "Thit kho (Braised pork)": ("vn_nin_2017", "NIN: Thịt lợn ba chỉ kho tàu (nin_dish_693a681731cab0f3540c9978) [basis: per_100g_mapping_derived]"),
    "Thit nuong (Grilled meat)": ("vn_nin_2017", "NIN: Thịt lợn xiên nướng (nin_dish_693b74e2c5b06f2f1b0b0864) [basis: per_100g_mapping_derived]"),
    "Tom (Shrimp)": ("vn_nin_2017", "NIN: Tôm đồng, tươi (nin_ing_6877a6b660d6c84e9bd5cc85) [basis: per_100g]"),
    "Trung (Egg)": ("vn_nin_2017", "NIN: Quả trứng gà, tươi (nin_ing_6877a6b660d6c84e9bd5cbce) [basis: per_100g]"),
    "Xoi (Sticky rice)": ("vn_nin_2017", "NIN: Xôi trắng miệng bát (nin_dish_694e3d69d2b36a66b1080cb3) [basis: per_100g]"),
}

class_names = [
    {
        "name": "Banh canh (Vietnamese thick noodle soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 75,
            "Protein": 3.8,
            "Fat": 2.5,
            "Carbs": 9.5,
            "Saturates": 0.6,
            "Sugar": 0.8,
            "Salt": 0.6,
            "Sodium": 110.6,
            "Calcium": 13.3,
            "Iron": 0.71,
            "Zinc": 0.3,
            "Cholesterol": 17.5,
        },
        "nutrition": {
            "Calories": 337.5,
            "Protein": 17.1,
            "Fat": 11.25,
            "Carbs": 42.75,
            "Saturates": 2.7,
            "Sugar": 3.6,
            "Salt": 2.7,
            "Sodium": 497.7,
            "Calcium": 59.85,
            "Iron": 3.19,
            "Zinc": 1.35,
            "Cholesterol": 78.75,
        },
    },
    {
        "name": "Banh chung (Square sticky rice cake)",
        "serving_type": "reference serving (200 g)",
        "serving_size_g": 200,
        "nutrition_per_100g": {
            "Calories": 195,
            "Protein": 4.5,
            "Fat": 3.8,
            "Carbs": 36,
            "Saturates": 1.2,
            "Sugar": 0.3,
            "Salt": 0.4,
            "Sodium": 0.0,
            "Calcium": 0.0,
            "Iron": 0.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 390,
            "Protein": 9,
            "Fat": 7.6,
            "Carbs": 72,
            "Saturates": 2.4,
            "Sugar": 0.6,
            "Salt": 0.8,
            "Sodium": 0.0,
            "Calcium": 0.0,
            "Iron": 0.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Banh cuon (Rolled rice pancake)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 125,
            "Protein": 3.5,
            "Fat": 4,
            "Carbs": 18,
            "Saturates": 1,
            "Sugar": 0.8,
            "Salt": 0.5,
            "Sodium": 45.8,
            "Calcium": 29.8,
            "Iron": 3.43,
            "Zinc": 0.11,
            "Cholesterol": 45.3,
        },
        "nutrition": {
            "Calories": 187.5,
            "Protein": 5.25,
            "Fat": 6,
            "Carbs": 27,
            "Saturates": 1.5,
            "Sugar": 1.2,
            "Salt": 0.75,
            "Sodium": 68.7,
            "Calcium": 44.7,
            "Iron": 5.15,
            "Zinc": 0.17,
            "Cholesterol": 67.95,
        },
    },
    {
        "name": "Banh khot (Mini savory pancakes)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 195,
            "Protein": 4,
            "Fat": 9.5,
            "Carbs": 23.5,
            "Saturates": 2,
            "Sugar": 1.8,
            "Salt": 0.7,
            "Sodium": 276.0,
            "Calcium": 35.0,
            "Iron": 0.8,
            "Zinc": 0.6,
            "Cholesterol": 25.0,
        },
        "nutrition": {
            "Calories": 292.5,
            "Protein": 6,
            "Fat": 14.25,
            "Carbs": 35.25,
            "Saturates": 3,
            "Sugar": 2.7,
            "Salt": 1.05,
            "Sodium": 414.0,
            "Calcium": 52.5,
            "Iron": 1.2,
            "Zinc": 0.9,
            "Cholesterol": 37.5,
        },
    },
    {
        "name": "Banh mi (Vietnamese baguette sandwich)",
        "serving_type": "reference serving (200 g)",
        "serving_size_g": 200,
        "nutrition_per_100g": {
            "Calories": 265,
            "Protein": 8.5,
            "Fat": 9.8,
            "Carbs": 36,
            "Saturates": 3,
            "Sugar": 3,
            "Salt": 1.1,
            "Sodium": 50.8,
            "Calcium": 53.0,
            "Iron": 6.73,
            "Zinc": 0.13,
            "Cholesterol": 208.3,
        },
        "nutrition": {
            "Calories": 530,
            "Protein": 17,
            "Fat": 19.6,
            "Carbs": 72,
            "Saturates": 6,
            "Sugar": 6,
            "Salt": 2.2,
            "Sodium": 101.6,
            "Calcium": 106.0,
            "Iron": 13.46,
            "Zinc": 0.26,
            "Cholesterol": 416.6,
        },
    },
    {
        "name": "Banh trang (Rice paper)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 333,
            "Protein": 0.5,
            "Fat": 0.2,
            "Carbs": 82,
            "Saturates": 0.1,
            "Sugar": 0,
            "Salt": 0.2,
            "Sodium": 0.0,
            "Calcium": 20.0,
            "Iron": 0.3,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 333,
            "Protein": 0.5,
            "Fat": 0.2,
            "Carbs": 82,
            "Saturates": 0.1,
            "Sugar": 0,
            "Salt": 0.2,
            "Sodium": 0.0,
            "Calcium": 20.0,
            "Iron": 0.3,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Banh trang tron (Rice paper salad)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 160,
            "Protein": 4,
            "Fat": 6.5,
            "Carbs": 21,
            "Saturates": 1,
            "Sugar": 2,
            "Salt": 0.8,
            "Sodium": 271.5,
            "Calcium": 114.6,
            "Iron": 2.33,
            "Zinc": 0.8,
            "Cholesterol": 235.2,
        },
        "nutrition": {
            "Calories": 240,
            "Protein": 6,
            "Fat": 9.75,
            "Carbs": 31.5,
            "Saturates": 1.5,
            "Sugar": 3,
            "Salt": 1.2,
            "Sodium": 407.25,
            "Calcium": 171.9,
            "Iron": 3.5,
            "Zinc": 1.2,
            "Cholesterol": 352.8,
        },
    },
    {
        "name": "Banh xeo (Vietnamese sizzling pancake)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 190,
            "Protein": 5,
            "Fat": 9.5,
            "Carbs": 21,
            "Saturates": 2.8,
            "Sugar": 1.5,
            "Salt": 0.7,
            "Sodium": 411.9,
            "Calcium": 64.9,
            "Iron": 3.09,
            "Zinc": 2.1,
            "Cholesterol": 15.6,
        },
        "nutrition": {
            "Calories": 285,
            "Protein": 7.5,
            "Fat": 14.25,
            "Carbs": 31.5,
            "Saturates": 4.2,
            "Sugar": 2.25,
            "Salt": 1.05,
            "Sodium": 617.85,
            "Calcium": 97.35,
            "Iron": 4.63,
            "Zinc": 3.15,
            "Cholesterol": 23.4,
        },
    },
    {
        "name": "Bo kho (Beef stew)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 115,
            "Protein": 9.5,
            "Fat": 5.8,
            "Carbs": 6,
            "Saturates": 2.2,
            "Sugar": 1.5,
            "Salt": 0.9,
            "Sodium": 464.6,
            "Calcium": 58.6,
            "Iron": 5.42,
            "Zinc": 1.72,
            "Cholesterol": 47.0,
        },
        "nutrition": {
            "Calories": 172.5,
            "Protein": 14.25,
            "Fat": 8.7,
            "Carbs": 9,
            "Saturates": 3.3,
            "Sugar": 2.25,
            "Salt": 1.35,
            "Sodium": 696.9,
            "Calcium": 87.9,
            "Iron": 8.13,
            "Zinc": 2.58,
            "Cholesterol": 70.5,
        },
    },
    {
        "name": "Bo la lot (Grilled beef wrapped in betel leaves)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 175,
            "Protein": 12,
            "Fat": 11,
            "Carbs": 5,
            "Saturates": 3.5,
            "Sugar": 1.2,
            "Salt": 0.8,
            "Sodium": 1032.7,
            "Calcium": 105.9,
            "Iron": 1.97,
            "Zinc": 2.0,
            "Cholesterol": 28.6,
        },
        "nutrition": {
            "Calories": 262.5,
            "Protein": 18,
            "Fat": 16.5,
            "Carbs": 7.5,
            "Saturates": 5.25,
            "Sugar": 1.8,
            "Salt": 1.2,
            "Sodium": 1549.05,
            "Calcium": 158.85,
            "Iron": 2.96,
            "Zinc": 3.0,
            "Cholesterol": 42.9,
        },
    },
    {
        "name": "Bong cai (Cauliflower)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 25,
            "Protein": 2,
            "Fat": 0.1,
            "Carbs": 5,
            "Saturates": 0,
            "Sugar": 2,
            "Salt": 0.02,
            "Sodium": 20.0,
            "Calcium": 26.0,
            "Iron": 1.4,
            "Zinc": 0.2,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 25,
            "Protein": 2,
            "Fat": 0.1,
            "Carbs": 5,
            "Saturates": 0,
            "Sugar": 2,
            "Salt": 0.02,
            "Sodium": 20.0,
            "Calcium": 26.0,
            "Iron": 1.4,
            "Zinc": 0.2,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Bun (Rice vermicelli)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 109,
            "Protein": 1.8,
            "Fat": 0.2,
            "Carbs": 24.9,
            "Saturates": 0.1,
            "Sugar": 0.1,
            "Salt": 0.02,
            "Sodium": 0.0,
            "Calcium": 12.0,
            "Iron": 0.2,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 109,
            "Protein": 1.8,
            "Fat": 0.2,
            "Carbs": 24.9,
            "Saturates": 0.1,
            "Sugar": 0.1,
            "Salt": 0.02,
            "Sodium": 0.0,
            "Calcium": 12.0,
            "Iron": 0.2,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Bun bo Hue (Hue beef noodle soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 90,
            "Protein": 5.5,
            "Fat": 3.5,
            "Carbs": 9,
            "Saturates": 1,
            "Sugar": 0.6,
            "Salt": 0.9,
            "Sodium": 152.6,
            "Calcium": 18.0,
            "Iron": 3.98,
            "Zinc": 0.36,
            "Cholesterol": 10.1,
        },
        "nutrition": {
            "Calories": 405,
            "Protein": 24.75,
            "Fat": 15.75,
            "Carbs": 40.5,
            "Saturates": 4.5,
            "Sugar": 2.7,
            "Salt": 4.05,
            "Sodium": 686.7,
            "Calcium": 81.0,
            "Iron": 17.91,
            "Zinc": 1.62,
            "Cholesterol": 45.45,
        },
    },
    {
        "name": "Bun cha (Grilled pork with vermicelli)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 136,
            "Protein": 6.1,
            "Fat": 4.4,
            "Carbs": 17.9,
            "Saturates": 2,
            "Sugar": 2,
            "Salt": 0.8,
            "Sodium": 258.2,
            "Calcium": 22.4,
            "Iron": 0.5,
            "Zinc": 0.57,
            "Cholesterol": 14.9,
        },
        "nutrition": {
            "Calories": 204,
            "Protein": 9.15,
            "Fat": 6.6,
            "Carbs": 26.85,
            "Saturates": 3,
            "Sugar": 3,
            "Salt": 1.2,
            "Sodium": 387.3,
            "Calcium": 33.6,
            "Iron": 0.75,
            "Zinc": 0.85,
            "Cholesterol": 22.35,
        },
    },
    {
        "name": "Bun dau (Vermicelli with tofu)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 150,
            "Protein": 6.5,
            "Fat": 7.5,
            "Carbs": 15,
            "Saturates": 1.2,
            "Sugar": 1,
            "Salt": 0.8,
            "Sodium": 245.8,
            "Calcium": 94.9,
            "Iron": 1.9,
            "Zinc": 0.65,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 225,
            "Protein": 9.75,
            "Fat": 11.25,
            "Carbs": 22.5,
            "Saturates": 1.8,
            "Sugar": 1.5,
            "Salt": 1.2,
            "Sodium": 368.7,
            "Calcium": 142.35,
            "Iron": 2.85,
            "Zinc": 0.98,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Bun mam (Fermented fish noodle soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 92,
            "Protein": 5.2,
            "Fat": 3.6,
            "Carbs": 10,
            "Saturates": 0.8,
            "Sugar": 1,
            "Salt": 1.2,
            "Sodium": 189.0,
            "Calcium": 26.5,
            "Iron": 0.49,
            "Zinc": 0.24,
            "Cholesterol": 28.0,
        },
        "nutrition": {
            "Calories": 414,
            "Protein": 23.4,
            "Fat": 16.2,
            "Carbs": 45,
            "Saturates": 3.6,
            "Sugar": 4.5,
            "Salt": 5.4,
            "Sodium": 850.5,
            "Calcium": 119.25,
            "Iron": 2.21,
            "Zinc": 1.08,
            "Cholesterol": 126.0,
        },
    },
    {
        "name": "Bun rieu (Crab noodle soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 85,
            "Protein": 4.8,
            "Fat": 3.2,
            "Carbs": 9.2,
            "Saturates": 0.7,
            "Sugar": 0.8,
            "Salt": 0.8,
            "Sodium": 483.6,
            "Calcium": 14.0,
            "Iron": 0.18,
            "Zinc": 0.01,
            "Cholesterol": 0.7,
        },
        "nutrition": {
            "Calories": 382.5,
            "Protein": 21.6,
            "Fat": 14.4,
            "Carbs": 41.4,
            "Saturates": 3.15,
            "Sugar": 3.6,
            "Salt": 3.6,
            "Sodium": 2176.2,
            "Calcium": 63.0,
            "Iron": 0.81,
            "Zinc": 0.04,
            "Cholesterol": 3.15,
        },
    },
    {
        "name": "Ca (Fish)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 130,
            "Protein": 18,
            "Fat": 5,
            "Carbs": 0,
            "Saturates": 1.2,
            "Sugar": 0,
            "Salt": 0.3,
            "Sodium": 49.0,
            "Calcium": 17.0,
            "Iron": 0.9,
            "Zinc": 1.48,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 130,
            "Protein": 18,
            "Fat": 5,
            "Carbs": 0,
            "Saturates": 1.2,
            "Sugar": 0,
            "Salt": 0.3,
            "Sodium": 49.0,
            "Calcium": 17.0,
            "Iron": 0.9,
            "Zinc": 1.48,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Ca chua (Tomato)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 18,
            "Protein": 0.9,
            "Fat": 0.2,
            "Carbs": 3.9,
            "Saturates": 0,
            "Sugar": 2.6,
            "Salt": 0.01,
            "Sodium": 12.2,
            "Calcium": 12.0,
            "Iron": 1.4,
            "Zinc": 0.74,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 18,
            "Protein": 0.9,
            "Fat": 0.2,
            "Carbs": 3.9,
            "Saturates": 0,
            "Sugar": 2.6,
            "Salt": 0.01,
            "Sodium": 12.2,
            "Calcium": 12.0,
            "Iron": 1.4,
            "Zinc": 0.74,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Ca phao (Pickled eggplant)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 22,
            "Protein": 1,
            "Fat": 0.2,
            "Carbs": 4.5,
            "Saturates": 0,
            "Sugar": 1.5,
            "Salt": 1.5,
            "Sodium": 0.0,
            "Calcium": 15.0,
            "Iron": 0.8,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 22,
            "Protein": 1,
            "Fat": 0.2,
            "Carbs": 4.5,
            "Saturates": 0,
            "Sugar": 1.5,
            "Salt": 1.5,
            "Sodium": 0.0,
            "Calcium": 15.0,
            "Iron": 0.8,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Ca rot (Carrot)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 41,
            "Protein": 0.9,
            "Fat": 0.2,
            "Carbs": 9.6,
            "Saturates": 0,
            "Sugar": 4.7,
            "Salt": 0.07,
            "Sodium": 52.0,
            "Calcium": 43.0,
            "Iron": 0.8,
            "Zinc": 1.11,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 41,
            "Protein": 0.9,
            "Fat": 0.2,
            "Carbs": 9.6,
            "Saturates": 0,
            "Sugar": 4.7,
            "Salt": 0.07,
            "Sodium": 52.0,
            "Calcium": 43.0,
            "Iron": 0.8,
            "Zinc": 1.11,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Canh (Soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 35,
            "Protein": 2.5,
            "Fat": 1.2,
            "Carbs": 3.5,
            "Saturates": 0.3,
            "Sugar": 1,
            "Salt": 0.6,
            "Sodium": 206.5,
            "Calcium": 43.9,
            "Iron": 0.85,
            "Zinc": 0.45,
            "Cholesterol": 6.8,
        },
        "nutrition": {
            "Calories": 157.5,
            "Protein": 11.25,
            "Fat": 5.4,
            "Carbs": 15.75,
            "Saturates": 1.35,
            "Sugar": 4.5,
            "Salt": 2.7,
            "Sodium": 929.25,
            "Calcium": 197.55,
            "Iron": 3.82,
            "Zinc": 2.02,
            "Cholesterol": 30.6,
        },
    },
    {
        "name": "Cha (Vietnamese pork roll)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 180,
            "Protein": 14,
            "Fat": 12,
            "Carbs": 3,
            "Saturates": 4,
            "Sugar": 1,
            "Salt": 1.5,
            "Sodium": 0.0,
            "Calcium": 0.0,
            "Iron": 0.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 180,
            "Protein": 14,
            "Fat": 12,
            "Carbs": 3,
            "Saturates": 4,
            "Sugar": 1,
            "Salt": 1.5,
            "Sodium": 0.0,
            "Calcium": 0.0,
            "Iron": 0.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Cha gio (Spring rolls)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 240,
            "Protein": 7.5,
            "Fat": 14,
            "Carbs": 21,
            "Saturates": 3,
            "Sugar": 1.8,
            "Salt": 0.9,
            "Sodium": 15.0,
            "Calcium": 35.0,
            "Iron": 1.49,
            "Zinc": 0.83,
            "Cholesterol": 24.2,
        },
        "nutrition": {
            "Calories": 360,
            "Protein": 11.25,
            "Fat": 21,
            "Carbs": 31.5,
            "Saturates": 4.5,
            "Sugar": 2.7,
            "Salt": 1.35,
            "Sodium": 22.5,
            "Calcium": 52.5,
            "Iron": 2.23,
            "Zinc": 1.24,
            "Cholesterol": 36.3,
        },
    },
    {
        "name": "Chanh (Lime)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 30,
            "Protein": 0.7,
            "Fat": 0.2,
            "Carbs": 10.5,
            "Saturates": 0,
            "Sugar": 1.7,
            "Salt": 0.01,
            "Sodium": 3.0,
            "Calcium": 40.0,
            "Iron": 0.6,
            "Zinc": 0.1,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 30,
            "Protein": 0.7,
            "Fat": 0.2,
            "Carbs": 10.5,
            "Saturates": 0,
            "Sugar": 1.7,
            "Salt": 0.01,
            "Sodium": 3.0,
            "Calcium": 40.0,
            "Iron": 0.6,
            "Zinc": 0.1,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Com (Rice)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 130,
            "Protein": 2.7,
            "Fat": 0.3,
            "Carbs": 28.2,
            "Saturates": 0.1,
            "Sugar": 0.1,
            "Salt": 0.01,
            "Sodium": 1.3,
            "Calcium": 7.7,
            "Iron": 0.33,
            "Zinc": 0.38,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 130,
            "Protein": 2.7,
            "Fat": 0.3,
            "Carbs": 28.2,
            "Saturates": 0.1,
            "Sugar": 0.1,
            "Salt": 0.01,
            "Sodium": 1.3,
            "Calcium": 7.7,
            "Iron": 0.33,
            "Zinc": 0.38,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Com tam (Broken rice)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 165,
            "Protein": 7,
            "Fat": 5,
            "Carbs": 24,
            "Saturates": 1.5,
            "Sugar": 1,
            "Salt": 0.9,
            "Sodium": 21.0,
            "Calcium": 17.5,
            "Iron": 0.86,
            "Zinc": 1.66,
            "Cholesterol": 18.4,
        },
        "nutrition": {
            "Calories": 247.5,
            "Protein": 10.5,
            "Fat": 7.5,
            "Carbs": 36,
            "Saturates": 2.25,
            "Sugar": 1.5,
            "Salt": 1.35,
            "Sodium": 31.5,
            "Calcium": 26.25,
            "Iron": 1.29,
            "Zinc": 2.49,
            "Cholesterol": 27.6,
        },
    },
    {
        "name": "Con nguoi (Human)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 0,
            "Protein": 0,
            "Fat": 0,
            "Carbs": 0,
            "Saturates": 0,
            "Sugar": 0,
            "Salt": 0,
            "Sodium": 0.0,
            "Calcium": 0.0,
            "Iron": 0.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 0,
            "Protein": 0,
            "Fat": 0,
            "Carbs": 0,
            "Saturates": 0,
            "Sugar": 0,
            "Salt": 0,
            "Sodium": 0.0,
            "Calcium": 0.0,
            "Iron": 0.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Cu kieu (Pickled scallion head)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 35,
            "Protein": 1.2,
            "Fat": 0.1,
            "Carbs": 7.5,
            "Saturates": 0,
            "Sugar": 4,
            "Salt": 1.2,
            "Sodium": 812.0,
            "Calcium": 50.0,
            "Iron": 1.2,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 35,
            "Protein": 1.2,
            "Fat": 0.1,
            "Carbs": 7.5,
            "Saturates": 0,
            "Sugar": 4,
            "Salt": 1.2,
            "Sodium": 812.0,
            "Calcium": 50.0,
            "Iron": 1.2,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Cua (Crab)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 87,
            "Protein": 18,
            "Fat": 1.1,
            "Carbs": 0,
            "Saturates": 0.2,
            "Sugar": 0,
            "Salt": 0.5,
            "Sodium": 1484.0,
            "Calcium": 826.0,
            "Iron": 1.4,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 87,
            "Protein": 18,
            "Fat": 1.1,
            "Carbs": 0,
            "Saturates": 0.2,
            "Sugar": 0,
            "Salt": 0.5,
            "Sodium": 1484.0,
            "Calcium": 826.0,
            "Iron": 1.4,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Dau hu (Tofu)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 76,
            "Protein": 8,
            "Fat": 4.8,
            "Carbs": 1.9,
            "Saturates": 0.7,
            "Sugar": 0.5,
            "Salt": 0.02,
            "Sodium": 7.0,
            "Calcium": 24.0,
            "Iron": 2.2,
            "Zinc": 0.8,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 76,
            "Protein": 8,
            "Fat": 4.8,
            "Carbs": 1.9,
            "Saturates": 0.7,
            "Sugar": 0.5,
            "Salt": 0.02,
            "Sodium": 7.0,
            "Calcium": 24.0,
            "Iron": 2.2,
            "Zinc": 0.8,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Dua chua (Pickled vegetables)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 20,
            "Protein": 1,
            "Fat": 0.2,
            "Carbs": 3.5,
            "Saturates": 0,
            "Sugar": 1.5,
            "Salt": 1.5,
            "Sodium": 0.0,
            "Calcium": 100.0,
            "Iron": 3.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 20,
            "Protein": 1,
            "Fat": 0.2,
            "Carbs": 3.5,
            "Saturates": 0,
            "Sugar": 1.5,
            "Salt": 1.5,
            "Sodium": 0.0,
            "Calcium": 100.0,
            "Iron": 3.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Dua leo (Cucumber)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 15,
            "Protein": 0.7,
            "Fat": 0.1,
            "Carbs": 3.6,
            "Saturates": 0,
            "Sugar": 1.7,
            "Salt": 0.01,
            "Sodium": 13.3,
            "Calcium": 23.0,
            "Iron": 1.0,
            "Zinc": 0.18,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 15,
            "Protein": 0.7,
            "Fat": 0.1,
            "Carbs": 3.6,
            "Saturates": 0,
            "Sugar": 1.7,
            "Salt": 0.01,
            "Sodium": 13.3,
            "Calcium": 23.0,
            "Iron": 1.0,
            "Zinc": 0.18,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Goi cuon (Fresh spring rolls)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 115,
            "Protein": 5.5,
            "Fat": 2.5,
            "Carbs": 18,
            "Saturates": 0.5,
            "Sugar": 1.8,
            "Salt": 0.6,
            "Sodium": 271.5,
            "Calcium": 114.6,
            "Iron": 2.33,
            "Zinc": 0.8,
            "Cholesterol": 235.2,
        },
        "nutrition": {
            "Calories": 172.5,
            "Protein": 8.25,
            "Fat": 3.75,
            "Carbs": 27,
            "Saturates": 0.75,
            "Sugar": 2.7,
            "Salt": 0.9,
            "Sodium": 407.25,
            "Calcium": 171.9,
            "Iron": 3.5,
            "Zinc": 1.2,
            "Cholesterol": 352.8,
        },
    },
    {
        "name": "Hamburger",
        "serving_type": "reference serving (200 g)",
        "serving_size_g": 200,
        "nutrition_per_100g": {
            "Calories": 250,
            "Protein": 13,
            "Fat": 12,
            "Carbs": 24,
            "Saturates": 4.5,
            "Sugar": 4,
            "Salt": 1.2,
            "Sodium": 258.1,
            "Calcium": 140.6,
            "Iron": 1.67,
            "Zinc": 1.33,
            "Cholesterol": 10.5,
        },
        "nutrition": {
            "Calories": 500,
            "Protein": 26,
            "Fat": 24,
            "Carbs": 48,
            "Saturates": 9,
            "Sugar": 8,
            "Salt": 2.4,
            "Sodium": 516.2,
            "Calcium": 281.2,
            "Iron": 3.34,
            "Zinc": 2.66,
            "Cholesterol": 21.0,
        },
    },
    {
        "name": "Heo quay (Roast pork)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 290,
            "Protein": 18,
            "Fat": 23,
            "Carbs": 1.5,
            "Saturates": 8,
            "Sugar": 0.5,
            "Salt": 1.1,
            "Sodium": 534.6,
            "Calcium": 20.7,
            "Iron": 2.73,
            "Zinc": 6.0,
            "Cholesterol": 178.4,
        },
        "nutrition": {
            "Calories": 290,
            "Protein": 18,
            "Fat": 23,
            "Carbs": 1.5,
            "Saturates": 8,
            "Sugar": 0.5,
            "Salt": 1.1,
            "Sodium": 534.6,
            "Calcium": 20.7,
            "Iron": 2.73,
            "Zinc": 6.0,
            "Cholesterol": 178.4,
        },
    },
    {
        "name": "Hu tieu (Clear rice noodle soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 88,
            "Protein": 5,
            "Fat": 3,
            "Carbs": 10,
            "Saturates": 0.8,
            "Sugar": 1,
            "Salt": 0.8,
            "Sodium": 354.7,
            "Calcium": 39.0,
            "Iron": 1.51,
            "Zinc": 0.87,
            "Cholesterol": 72.6,
        },
        "nutrition": {
            "Calories": 396,
            "Protein": 22.5,
            "Fat": 13.5,
            "Carbs": 45,
            "Saturates": 3.6,
            "Sugar": 4.5,
            "Salt": 3.6,
            "Sodium": 1596.15,
            "Calcium": 175.5,
            "Iron": 6.79,
            "Zinc": 3.92,
            "Cholesterol": 326.7,
        },
    },
    {
        "name": "Kho qua thit (Stuffed bitter melon soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 65,
            "Protein": 5,
            "Fat": 3.2,
            "Carbs": 4,
            "Saturates": 1,
            "Sugar": 1.5,
            "Salt": 0.7,
            "Sodium": 167.8,
            "Calcium": 19.2,
            "Iron": 1.64,
            "Zinc": 0.8,
            "Cholesterol": 9.5,
        },
        "nutrition": {
            "Calories": 292.5,
            "Protein": 22.5,
            "Fat": 14.4,
            "Carbs": 18,
            "Saturates": 4.5,
            "Sugar": 6.75,
            "Salt": 3.15,
            "Sodium": 755.1,
            "Calcium": 86.4,
            "Iron": 7.38,
            "Zinc": 3.6,
            "Cholesterol": 42.75,
        },
    },
    {
        "name": "Khoai tay chien (French fries)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 312,
            "Protein": 3.4,
            "Fat": 15,
            "Carbs": 41,
            "Saturates": 2.3,
            "Sugar": 0.3,
            "Salt": 0.6,
            "Sodium": 387.5,
            "Calcium": 9.0,
            "Iron": 1.0,
            "Zinc": 0.24,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 312,
            "Protein": 3.4,
            "Fat": 15,
            "Carbs": 41,
            "Saturates": 2.3,
            "Sugar": 0.3,
            "Salt": 0.6,
            "Sodium": 387.5,
            "Calcium": 9.0,
            "Iron": 1.0,
            "Zinc": 0.24,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Lau (Hotpot)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 90,
            "Protein": 6.5,
            "Fat": 4,
            "Carbs": 7,
            "Saturates": 1.2,
            "Sugar": 1,
            "Salt": 1,
            "Sodium": 1414.4,
            "Calcium": 205.6,
            "Iron": 8.05,
            "Zinc": 2.67,
            "Cholesterol": 665.6,
        },
        "nutrition": {
            "Calories": 405,
            "Protein": 29.25,
            "Fat": 18,
            "Carbs": 31.5,
            "Saturates": 5.4,
            "Sugar": 4.5,
            "Salt": 4.5,
            "Sodium": 6364.8,
            "Calcium": 925.2,
            "Iron": 36.23,
            "Zinc": 12.02,
            "Cholesterol": 2995.2,
        },
    },
    {
        "name": "Long heo (Pork offal)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 140,
            "Protein": 15,
            "Fat": 8,
            "Carbs": 1,
            "Saturates": 2.8,
            "Sugar": 0,
            "Salt": 0.4,
            "Sodium": 41.3,
            "Calcium": 41.0,
            "Iron": 2.5,
            "Zinc": 1.2,
            "Cholesterol": 1197.0,
        },
        "nutrition": {
            "Calories": 140,
            "Protein": 15,
            "Fat": 8,
            "Carbs": 1,
            "Saturates": 2.8,
            "Sugar": 0,
            "Salt": 0.4,
            "Sodium": 41.3,
            "Calcium": 41.0,
            "Iron": 2.5,
            "Zinc": 1.2,
            "Cholesterol": 1197.0,
        },
    },
    {
        "name": "Mi (Egg noodles)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 138,
            "Protein": 4.5,
            "Fat": 2.1,
            "Carbs": 25,
            "Saturates": 0.5,
            "Sugar": 0.8,
            "Salt": 0.3,
            "Sodium": 0.0,
            "Calcium": 34.0,
            "Iron": 1.5,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 138,
            "Protein": 4.5,
            "Fat": 2.1,
            "Carbs": 25,
            "Saturates": 0.5,
            "Sugar": 0.8,
            "Salt": 0.3,
            "Sodium": 0.0,
            "Calcium": 34.0,
            "Iron": 1.5,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Muc (Squid)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 92,
            "Protein": 15.6,
            "Fat": 1.4,
            "Carbs": 3.1,
            "Saturates": 0.4,
            "Sugar": 0,
            "Salt": 0.4,
            "Sodium": 44.0,
            "Calcium": 14.0,
            "Iron": 0.6,
            "Zinc": 0.7,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 92,
            "Protein": 15.6,
            "Fat": 1.4,
            "Carbs": 3.1,
            "Saturates": 0.4,
            "Sugar": 0,
            "Salt": 0.4,
            "Sodium": 44.0,
            "Calcium": 14.0,
            "Iron": 0.6,
            "Zinc": 0.7,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Nam (Mushroom)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 28,
            "Protein": 3,
            "Fat": 0.3,
            "Carbs": 4.5,
            "Saturates": 0,
            "Sugar": 1.8,
            "Salt": 0.01,
            "Sodium": 0.0,
            "Calcium": 27.0,
            "Iron": 5.2,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 28,
            "Protein": 3,
            "Fat": 0.3,
            "Carbs": 4.5,
            "Saturates": 0,
            "Sugar": 1.8,
            "Salt": 0.01,
            "Sodium": 0.0,
            "Calcium": 27.0,
            "Iron": 5.2,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Oc (Snails)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 79,
            "Protein": 15,
            "Fat": 1.4,
            "Carbs": 2,
            "Saturates": 0.3,
            "Sugar": 0,
            "Salt": 0.4,
            "Sodium": 0.0,
            "Calcium": 11.0,
            "Iron": 0.0,
            "Zinc": 1.1,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 79,
            "Protein": 15,
            "Fat": 1.4,
            "Carbs": 2,
            "Saturates": 0.3,
            "Sugar": 0,
            "Salt": 0.4,
            "Sodium": 0.0,
            "Calcium": 11.0,
            "Iron": 0.0,
            "Zinc": 1.1,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Ot chuong (Bell pepper)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 20,
            "Protein": 1,
            "Fat": 0.2,
            "Carbs": 4.6,
            "Saturates": 0,
            "Sugar": 4.2,
            "Salt": 0.02,
            "Sodium": 3.0,
            "Calcium": 6.0,
            "Iron": 0.8,
            "Zinc": 0.13,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 20,
            "Protein": 1,
            "Fat": 0.2,
            "Carbs": 4.6,
            "Saturates": 0,
            "Sugar": 4.2,
            "Salt": 0.02,
            "Sodium": 3.0,
            "Calcium": 6.0,
            "Iron": 0.8,
            "Zinc": 0.13,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Pho (Vietnamese noodle soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 75,
            "Protein": 5.0,
            "Fat": 2.0,
            "Carbs": 11.5,
            "Saturates": 0.7,
            "Sugar": 0.6,
            "Salt": 0.9,
            "Sodium": 583.2,
            "Calcium": 30.4,
            "Iron": 0.87,
            "Zinc": 1.04,
            "Cholesterol": 9.0,
        },
        "nutrition": {
            "Calories": 337.5,
            "Protein": 22.5,
            "Fat": 9.0,
            "Carbs": 51.75,
            "Saturates": 3.15,
            "Sugar": 2.7,
            "Salt": 4.05,
            "Sodium": 2624.4,
            "Calcium": 136.8,
            "Iron": 3.92,
            "Zinc": 4.68,
            "Cholesterol": 40.5,
        },
    },
    {
        "name": "Pho mai (Cheese)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 350,
            "Protein": 22,
            "Fat": 28,
            "Carbs": 2,
            "Saturates": 18,
            "Sugar": 1,
            "Salt": 1.6,
            "Sodium": 165.0,
            "Calcium": 115.0,
            "Iron": 0.0,
            "Zinc": 0.5,
            "Cholesterol": 61.0,
        },
        "nutrition": {
            "Calories": 350,
            "Protein": 22,
            "Fat": 28,
            "Carbs": 2,
            "Saturates": 18,
            "Sugar": 1,
            "Salt": 1.6,
            "Sodium": 165.0,
            "Calcium": 115.0,
            "Iron": 0.0,
            "Zinc": 0.5,
            "Cholesterol": 61.0,
        },
    },
    {
        "name": "Rau (Vegetables)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 25,
            "Protein": 1.5,
            "Fat": 0.2,
            "Carbs": 4.5,
            "Saturates": 0,
            "Sugar": 2,
            "Salt": 0.02,
            "Sodium": 37.4,
            "Calcium": 100.0,
            "Iron": 1.4,
            "Zinc": 0.35,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 25,
            "Protein": 1.5,
            "Fat": 0.2,
            "Carbs": 4.5,
            "Saturates": 0,
            "Sugar": 2,
            "Salt": 0.02,
            "Sodium": 37.4,
            "Calcium": 100.0,
            "Iron": 1.4,
            "Zinc": 0.35,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Salad (Salad)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 50,
            "Protein": 1.5,
            "Fat": 3,
            "Carbs": 4.5,
            "Saturates": 0.5,
            "Sugar": 2,
            "Salt": 0.3,
            "Sodium": 91.3,
            "Calcium": 37.3,
            "Iron": 2.0,
            "Zinc": 0.67,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 75,
            "Protein": 2.25,
            "Fat": 4.5,
            "Carbs": 6.75,
            "Saturates": 0.75,
            "Sugar": 3,
            "Salt": 0.45,
            "Sodium": 136.95,
            "Calcium": 55.95,
            "Iron": 3.0,
            "Zinc": 1.01,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Thit bo (Beef)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 215,
            "Protein": 26,
            "Fat": 12,
            "Carbs": 0,
            "Saturates": 4.8,
            "Sugar": 0,
            "Salt": 0.2,
            "Sodium": 83.0,
            "Calcium": 12.0,
            "Iron": 3.1,
            "Zinc": 2.2,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 215,
            "Protein": 26,
            "Fat": 12,
            "Carbs": 0,
            "Saturates": 4.8,
            "Sugar": 0,
            "Salt": 0.2,
            "Sodium": 83.0,
            "Calcium": 12.0,
            "Iron": 3.1,
            "Zinc": 2.2,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Thit ga (Chicken)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 190,
            "Protein": 29,
            "Fat": 7.4,
            "Carbs": 0,
            "Saturates": 2,
            "Sugar": 0,
            "Salt": 0.2,
            "Sodium": 70.0,
            "Calcium": 12.0,
            "Iron": 1.5,
            "Zinc": 1.5,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 190,
            "Protein": 29,
            "Fat": 7.4,
            "Carbs": 0,
            "Saturates": 2,
            "Sugar": 0,
            "Salt": 0.2,
            "Sodium": 70.0,
            "Calcium": 12.0,
            "Iron": 1.5,
            "Zinc": 1.5,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Thit heo (Pork)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 242,
            "Protein": 27,
            "Fat": 14,
            "Carbs": 0,
            "Saturates": 5,
            "Sugar": 0,
            "Salt": 0.2,
            "Sodium": 0.0,
            "Calcium": 20.1,
            "Iron": 0.57,
            "Zinc": 2.02,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 242,
            "Protein": 27,
            "Fat": 14,
            "Carbs": 0,
            "Saturates": 5,
            "Sugar": 0,
            "Salt": 0.2,
            "Sodium": 0.0,
            "Calcium": 20.1,
            "Iron": 0.57,
            "Zinc": 2.02,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Thit kho (Braised pork)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 220,
            "Protein": 15,
            "Fat": 16,
            "Carbs": 4,
            "Saturates": 5.5,
            "Sugar": 3,
            "Salt": 1.5,
            "Sodium": 795.3,
            "Calcium": 11.3,
            "Iron": 1.03,
            "Zinc": 1.27,
            "Cholesterol": 45.3,
        },
        "nutrition": {
            "Calories": 220,
            "Protein": 15,
            "Fat": 16,
            "Carbs": 4,
            "Saturates": 5.5,
            "Sugar": 3,
            "Salt": 1.5,
            "Sodium": 795.3,
            "Calcium": 11.3,
            "Iron": 1.03,
            "Zinc": 1.27,
            "Cholesterol": 45.3,
        },
    },
    {
        "name": "Thit nuong (Grilled meat)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 230,
            "Protein": 20,
            "Fat": 15,
            "Carbs": 2.5,
            "Saturates": 5,
            "Sugar": 2,
            "Salt": 1,
            "Sodium": 69.3,
            "Calcium": 9.2,
            "Iron": 1.17,
            "Zinc": 3.0,
            "Cholesterol": 72.5,
        },
        "nutrition": {
            "Calories": 230,
            "Protein": 20,
            "Fat": 15,
            "Carbs": 2.5,
            "Saturates": 5,
            "Sugar": 2,
            "Salt": 1,
            "Sodium": 69.3,
            "Calcium": 9.2,
            "Iron": 1.17,
            "Zinc": 3.0,
            "Cholesterol": 72.5,
        },
    },
    {
        "name": "Tom (Shrimp)",
        "serving_type": "reference serving (100 g)",
        "serving_size_g": 100,
        "nutrition_per_100g": {
            "Calories": 99,
            "Protein": 24,
            "Fat": 0.3,
            "Carbs": 0.2,
            "Saturates": 0.1,
            "Sugar": 0,
            "Salt": 0.4,
            "Sodium": 418.0,
            "Calcium": 73.0,
            "Iron": 2.2,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 99,
            "Protein": 24,
            "Fat": 0.3,
            "Carbs": 0.2,
            "Saturates": 0.1,
            "Sugar": 0,
            "Salt": 0.4,
            "Sodium": 418.0,
            "Calcium": 73.0,
            "Iron": 2.2,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Trung (Egg)",
        "serving_type": "reference serving (50 g)",
        "serving_size_g": 50,
        "nutrition_per_100g": {
            "Calories": 143,
            "Protein": 12.6,
            "Fat": 9.5,
            "Carbs": 0.7,
            "Saturates": 3.1,
            "Sugar": 0.4,
            "Salt": 0.32,
            "Sodium": 0.0,
            "Calcium": 101.0,
            "Iron": 0.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 71.5,
            "Protein": 6.3,
            "Fat": 4.75,
            "Carbs": 0.35,
            "Saturates": 1.55,
            "Sugar": 0.2,
            "Salt": 0.16,
            "Sodium": 0.0,
            "Calcium": 50.5,
            "Iron": 0.0,
            "Zinc": 0.0,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Xoi (Sticky rice)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 195,
            "Protein": 4.2,
            "Fat": 2.5,
            "Carbs": 39,
            "Saturates": 0.6,
            "Sugar": 0.3,
            "Salt": 0.2,
            "Sodium": 2.0,
            "Calcium": 9.5,
            "Iron": 0.72,
            "Zinc": 1.32,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 292.5,
            "Protein": 6.3,
            "Fat": 3.75,
            "Carbs": 58.5,
            "Saturates": 0.9,
            "Sugar": 0.45,
            "Salt": 0.3,
            "Sodium": 3.0,
            "Calcium": 14.25,
            "Iron": 1.08,
            "Zinc": 1.98,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Banh beo (Vietnamese savory steamed rice cake)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 120,
            "Protein": 3.8,
            "Fat": 3.5,
            "Carbs": 18,
            "Saturates": 0.8,
            "Sugar": 1.2,
            "Salt": 0.4,
            "Sodium": 617.5,
            "Calcium": 113.9,
            "Iron": 3.8,
            "Zinc": 0.87,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 180,
            "Protein": 5.7,
            "Fat": 5.25,
            "Carbs": 27,
            "Saturates": 1.2,
            "Sugar": 1.8,
            "Salt": 0.6,
            "Sodium": 926.25,
            "Calcium": 170.85,
            "Iron": 5.7,
            "Zinc": 1.3,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Cao lau (Cao lau noodles)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 135,
            "Protein": 6.8,
            "Fat": 4.5,
            "Carbs": 17,
            "Saturates": 1.2,
            "Sugar": 1,
            "Salt": 0.8,
            "Sodium": 315.0,
            "Calcium": 20.0,
            "Iron": 1.2,
            "Zinc": 1.1,
            "Cholesterol": 18.0,
        },
        "nutrition": {
            "Calories": 202.5,
            "Protein": 10.2,
            "Fat": 6.75,
            "Carbs": 25.5,
            "Saturates": 1.8,
            "Sugar": 1.5,
            "Salt": 1.2,
            "Sodium": 472.5,
            "Calcium": 30.0,
            "Iron": 1.8,
            "Zinc": 1.65,
            "Cholesterol": 27.0,
        },
    },
    {
        "name": "Mi Quang (Quang-style noodles)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 130,
            "Protein": 6,
            "Fat": 4.8,
            "Carbs": 16,
            "Saturates": 1.2,
            "Sugar": 1,
            "Salt": 0.7,
            "Sodium": 118.6,
            "Calcium": 12.9,
            "Iron": 0.38,
            "Zinc": 0.19,
            "Cholesterol": 34.9,
        },
        "nutrition": {
            "Calories": 195,
            "Protein": 9,
            "Fat": 7.2,
            "Carbs": 24,
            "Saturates": 1.8,
            "Sugar": 1.5,
            "Salt": 1.05,
            "Sodium": 177.9,
            "Calcium": 19.35,
            "Iron": 0.57,
            "Zinc": 0.29,
            "Cholesterol": 52.35,
        },
    },
    {
        "name": "Com chien duong chau (Yangzhou fried rice)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 175,
            "Protein": 4.5,
            "Fat": 6.5,
            "Carbs": 25,
            "Saturates": 1.5,
            "Sugar": 0.8,
            "Salt": 0.8,
            "Sodium": 431.7,
            "Calcium": 35.3,
            "Iron": 1.06,
            "Zinc": 0.69,
            "Cholesterol": 93.3,
        },
        "nutrition": {
            "Calories": 262.5,
            "Protein": 6.75,
            "Fat": 9.75,
            "Carbs": 37.5,
            "Saturates": 2.25,
            "Sugar": 1.2,
            "Salt": 1.2,
            "Sodium": 647.55,
            "Calcium": 52.95,
            "Iron": 1.59,
            "Zinc": 1.03,
            "Cholesterol": 139.95,
        },
    },
    {
        "name": "Bun cha ca (Fish cake noodle soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 95,
            "Protein": 5.5,
            "Fat": 3.2,
            "Carbs": 11,
            "Saturates": 0.8,
            "Sugar": 0.8,
            "Salt": 0.9,
            "Sodium": 327.8,
            "Calcium": 75.5,
            "Iron": 0.61,
            "Zinc": 0.14,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 427.5,
            "Protein": 24.75,
            "Fat": 14.4,
            "Carbs": 49.5,
            "Saturates": 3.6,
            "Sugar": 3.6,
            "Salt": 4.05,
            "Sodium": 1475.1,
            "Calcium": 339.75,
            "Iron": 2.75,
            "Zinc": 0.63,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Com chien ga (Fried rice with chicken)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 180,
            "Protein": 6.5,
            "Fat": 6.8,
            "Carbs": 23,
            "Saturates": 1.6,
            "Sugar": 0.8,
            "Salt": 0.8,
            "Sodium": 187.1,
            "Calcium": 69.8,
            "Iron": 2.33,
            "Zinc": 1.97,
            "Cholesterol": 116.1,
        },
        "nutrition": {
            "Calories": 270,
            "Protein": 9.75,
            "Fat": 10.2,
            "Carbs": 34.5,
            "Saturates": 2.4,
            "Sugar": 1.2,
            "Salt": 1.2,
            "Sodium": 280.65,
            "Calcium": 104.7,
            "Iron": 3.5,
            "Zinc": 2.96,
            "Cholesterol": 174.15,
        },
    },
    {
        "name": "Chao long (Pork organ congee)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 80,
            "Protein": 4.5,
            "Fat": 2.8,
            "Carbs": 9.5,
            "Saturates": 0.8,
            "Sugar": 0.5,
            "Salt": 0.7,
            "Sodium": 149.1,
            "Calcium": 8.7,
            "Iron": 6.22,
            "Zinc": 0.29,
            "Cholesterol": 11.2,
        },
        "nutrition": {
            "Calories": 120,
            "Protein": 6.75,
            "Fat": 4.2,
            "Carbs": 14.25,
            "Saturates": 1.2,
            "Sugar": 0.75,
            "Salt": 1.05,
            "Sodium": 223.65,
            "Calcium": 13.05,
            "Iron": 9.33,
            "Zinc": 0.43,
            "Cholesterol": 16.8,
        },
    },
    {
        "name": "Nom hoa chuoi (Banana blossom salad)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 65,
            "Protein": 2.5,
            "Fat": 3,
            "Carbs": 7,
            "Saturates": 0.5,
            "Sugar": 2.5,
            "Salt": 0.6,
            "Sodium": 131.6,
            "Calcium": 164.8,
            "Iron": 3.31,
            "Zinc": 2.06,
            "Cholesterol": 34.5,
        },
        "nutrition": {
            "Calories": 97.5,
            "Protein": 3.75,
            "Fat": 4.5,
            "Carbs": 10.5,
            "Saturates": 0.75,
            "Sugar": 3.75,
            "Salt": 0.9,
            "Sodium": 197.4,
            "Calcium": 247.2,
            "Iron": 4.96,
            "Zinc": 3.09,
            "Cholesterol": 51.75,
        },
    },
    {
        "name": "Nui xao bo (Stir-fried macaroni with beef)",
        "serving_type": "reference serving (150 g)",
        "serving_size_g": 150,
        "nutrition_per_100g": {
            "Calories": 160,
            "Protein": 7.5,
            "Fat": 6,
            "Carbs": 19,
            "Saturates": 2,
            "Sugar": 1.2,
            "Salt": 0.7,
            "Sodium": 6.0,
            "Calcium": 21.0,
            "Iron": 1.3,
            "Zinc": 1.41,
            "Cholesterol": 0.0,
        },
        "nutrition": {
            "Calories": 240,
            "Protein": 11.25,
            "Fat": 9,
            "Carbs": 28.5,
            "Saturates": 3,
            "Sugar": 1.8,
            "Salt": 1.05,
            "Sodium": 9.0,
            "Calcium": 31.5,
            "Iron": 1.95,
            "Zinc": 2.11,
            "Cholesterol": 0.0,
        },
    },
    {
        "name": "Sup cua (Crab soup)",
        "serving_type": "reference serving (450 g)",
        "serving_size_g": 450,
        "nutrition_per_100g": {
            "Calories": 70,
            "Protein": 4.5,
            "Fat": 2,
            "Carbs": 8.5,
            "Saturates": 0.4,
            "Sugar": 0.8,
            "Salt": 0.6,
            "Sodium": 4.6,
            "Calcium": 7.8,
            "Iron": 0.2,
            "Zinc": 0.07,
            "Cholesterol": 17.2,
        },
        "nutrition": {
            "Calories": 315,
            "Protein": 20.25,
            "Fat": 9,
            "Carbs": 38.25,
            "Saturates": 1.8,
            "Sugar": 3.6,
            "Salt": 2.7,
            "Sodium": 20.7,
            "Calcium": 35.1,
            "Iron": 0.9,
            "Zinc": 0.32,
            "Cholesterol": 77.4,
        },
    },
]
